### ISSUE TITLE
Problema apertura nuove finestre shell dallo script cli.py

### ISSUE THREAD

**Issue by AndreaBerce** [FIAV1/big-data-laboratory#2]
Ho seguito la procedura di installazione e ho provato ad avviare lo script cli.py.
La procedura di Download Engines funziona senza problemi come nella video lezione, ma quando avvio le varie procedure Start la shell crea e chiude immediatamente le nuove finestre e non consente di leggere eventuali errori avvenuti. Hai qualche consiglio da darmi?

**Comment by FIAV1** [comment]
Ciao Andrea, scusa il ritardo nella risposta.
Sei riuscito a far funzionare tutto?
Se non fosse così, per capire meglio gli errori conviene che avvii gli script a mano, li trovi tutti nella cartella `bin` e li puoi avviare eseguendo il comando `bash bin/<nome_script.sh>` dalla root del progetto.
Se sei più temerario, puoi avviare i servizi a mano con i comandi appositi, trovi tutti i comandi necessari nella documentazione dei vari engines.

**Comment by Misairuzame** [comment]
Anche a me all'inizio dava questo problema, il motivo è che non avevo settato correttamente pyenv, infatti quando digitavo python --version il risultato era 2.7.(qualcosa). Una volta sistemato e assicuratomi che la versione di python utilizzata globalmente fosse 3.7.7 le tab si sono aperte correttamente ed il progetto ha funzionato senza problemi.

**Comment by FIAV1** [comment]
@Misairuzame grazie nuovamente per il feedback; aggiungo un timer di 60 secondi dopo l'esecuzione di ogni script, così è possibile verificare qual'è l'errore prima che la finestra si chiuda. Creo subito la pr 💯
