### ISSUE TITLE
cURL segnala che alcuni certificati sono scaduti durante il download degli engine

### ISSUE THREAD

**Issue by Misairuzame** [FIAV1/big-data-laboratory#3]
Gent. Ing. Frigo,
Innanzitutto complimenti per l'ottima lezione di laboratorio su Big Data.
Dopo aver clonato la repo ho utilizzato l'interfaccia "cli.py" per scaricare gli engine richiesti.
A quel punto alcuni file non sono stati scaricati perchè cURL segnala che alcuni certificati sono scaduti. Non so se è un problema mio, ma ho sistemato annullando il controllo dei certificati aggiungendo ai comandi curl in /bin/download-engines.sh l'opzione -k.

**Comment by FIAV1** [comment]
Buongiorno,
Grazie mille per il feedback 😁👍
Non saprei dire esattamente dove stia il problema, però i link sono sufficientemente sicuri, quindi direi che la sua soluzione è valida (accettare connessioni non sicure ai server).
Creo subito una pr per questa issue 💯
